import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import zipfile
import tarfile

F=Path(__file__).resolve().parent
ROOT=F.parents[2]
sys.path.insert(0,str(F.parent/'runner-source/scripts'))
from linux_runner import run
from process_runner import workspace_workloads

assert not workspace_workloads(ROOT)
r=F/'runtime'
plugins=r/'itstools/plugins'
folder=F/'components'
folder.mkdir()
components=[('its-reach', next(plugins.glob('fr.lip6.move.gal.itstools.binaries*/bin/its-reach-linux64')), ['--help']),('z3',next(plugins.glob('fr.lip6.smt.z3.binaries*/bin/z3-linux64')),['-version']),('greatspn',r/'greatspn/bin/RGMEDD2',[])]
rows=[]
for name,path,args in components:
 log=folder/(name+'.log')
 wall,code,timeout,usage=run([str(path),*args],ROOT,5,log,2**31,cpus=[8],perf=True)
 text=log.read_text(errors='replace')
 rows.append(dict(name=name,command=[str(path),*args],wall_seconds=wall,exit_code=code,outer_timeout=timeout,resources=usage,log=text))
(folder/'rows.json').write_text(json.dumps(rows,indent=2)+'\n')
# Longer outer diagnostic retains the exact five-second internal solver setting.
f=F/'native-verified-cases/ef-false'
cmd=[str(ROOT/'vendor/venv/bin/python'),str(F.parent/'runner-source/scripts/its_original.py'),'--runtime-config',str(F/'runtime-native-config.json'),'--pnml',str(f/'model.pnml'),'--xml',str(f/'properties.xml'),'--property-id','ef-false','--artifacts',str(F/'negative-long-diagnostic'),'--seconds','5']
wall,code,timeout,usage=run(cmd,ROOT,15,F/'negative-long-diagnostic.log',2**31,cpus=[8],perf=True)
(F/'negative-long-diagnostic.json').write_text(json.dumps(dict(command=cmd,outer_seconds=15,internal_seconds=5,wall_seconds=wall,exit_code=code,outer_timeout=timeout,resources=usage),indent=2)+'\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
files={}
with zipfile.ZipFile(F/'archives/product.zip') as z:
 for item in z.infolist():
  if not item.is_dir():
   p=r/'itstools'/item.filename; expected=hashlib.sha256(z.read(item)).hexdigest();assert sha(p)==expected,str(p);files[str(p.relative_to(ROOT))]=expected
with tarfile.open(F/'archives/greatspn_linux.tar.gz') as t:
 for item in t:
  if item.isfile():
   p=r/'greatspn'/item.name;expected=hashlib.sha256(t.extractfile(item).read()).hexdigest();assert sha(p)==expected,str(p);files[str(p.relative_to(ROOT))]=expected
for p in [r/'itstools/its-tools-native',r/'BenchKit_head.sh',r/'runeclipse.sh',F/'runtime-native-config.json',F.parent/'runner-source/scripts/its_original.py',F.parent/'runner-source/scripts/its_adapter.py']:
 files[str(p.relative_to(ROOT))]=sha(p)
assert files[str((r/'itstools/its-tools-native').relative_to(ROOT))]=='a84feea4726890be2d0beb07031147703d8ff6e1da52f3742fcbff7cfea1abda'
ldd={};external={};pending=[ROOT/name for name in files]
pending += [Path(shutil.which(name)) for name in ['bash','ls','sed','perl']]
seen=set()
while pending:
 p=pending.pop()
 if str(p) in seen:continue
 seen.add(str(p))
 if not p.is_file():continue
 if not p.is_relative_to(ROOT):external[str(p)]=sha(p)
 with p.open('rb') as stream:magic=stream.read(4)
 if magic!=b'\x7fELF':continue
 answer=subprocess.run(['ldd',str(p)],capture_output=True,text=True)
 output=answer.stdout+answer.stderr;ldd[str(p)]=dict(exit_code=answer.returncode,output=output)
 for match in re.finditer(r'(/[^\s()]+)',output):
  lib=Path(match.group(1))
  if lib.is_file():pending.append(lib)
metadata=dict(status='pinned',runtime='Official GraalVM native image with pinned product plugins and GreatSPN',native_source_correspondence='Unverified; native and product obtained from official paired installation URLs on 2026-10-04. Product SHA matches prior pin.',product_application='1.0.0.202609112134',wrapper_commit='1b883d1273df87f7523b9c016e7bc1a8733d9b8e',jvm_invoked=False,flags=['-its','-order','META','-manyOrder','-smt'],cpu_affinity=[8],memory_bytes=2**31,osgi_cache='Generated by failed JVM trials; unused by native and excluded from immutable pins',all_descendants='linux_runner control-group cleanup',missing_ldd=[p for p,v in ldd.items() if 'not found' in v['output']])
(F/'final-runtime-files-sha256.json').write_text(json.dumps(files,indent=2)+'\n')
(F/'external-files-sha256.json').write_text(json.dumps(external,indent=2)+'\n')
(F/'ldd.json').write_text(json.dumps(ldd,indent=2)+'\n')
(F/'final-runtime-metadata.json').write_text(json.dumps(metadata,indent=2)+'\n')
assert not workspace_workloads(ROOT)
print(json.dumps(dict(runtime_files=len(files),external_files=len(external),components=[dict(name=row['name'],exit_code=row['exit_code'],timeout=row['outer_timeout']) for row in rows],missing_ldd=metadata['missing_ldd'])),flush=True)
